project:
  type: book
  output-dir: docs

book:
  title: "JGTestBook"
  author: "Jill G"
  date: "16-5-2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "deel 1"
      chapters:
      - summary.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: litera
  pdf:
    documentclass: scrreprt

editor: visual

